export const getValidAggreagtionKeysbySiteName = (siteName?: string) => {
  switch (siteName) {
    case 'South Fort Chevrolet':
      return [
        'drivetrain',
        'miles',
        'dealername',
        'type',
        'display_price',
        'make',
        'model',
        'extcolorgeneric',
        'int_colorgeneric',
        'body',
        'year',
        'trim',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
      ];
    case 'Barrhead Ford':
    case 'Whitecourt Ford':
      return [
        'dealername',
        'type',
        'display_price',
        'make',
        'model',
        'extcolorgeneric',
        'standardbody',
        'drivetrain',
        'year',
        'trim',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
      ];
    case 'Wolfe Chevrolet GMC Buick Calgary':
      return [
        'dealername',
        'type',
        'dealername',
        'type',
        'display_price',
        'make',
        'model',
        'extcolorgeneric',
        'body',
        'year',
        'trim',
        'engdescription',
        'fueltype',
        'priority_option',
        'dealer_offer',
        'int_colorgeneric',
      ];
    case 'Canada Cadillac Version 1':
    case 'Tubman Chevrolet':
      return [
        'type',
        'display_price',
        'make',
        'model',
        'extcolorgeneric',
        'standardbody',
        'drivetrain',
        'year',
        'trim',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
      ];
    case 'Carter Cadillac':
    case 'Murray Cadillac Abbotsford':
      return [
        'type',
        'display_price',
        'make',
        'model',
        'extcolorgeneric',
        'standardbody',
        'drivetrain',
        'year',
        'trim',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
      ];
    case 'Right Toyota':
      return [
        'type',
        'display_price',
        'make',
        'model',
        'extcolorgeneric',
        'standardbody',
        'drivetrain',
        'year',
        'trim',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
        'option_package',
      ];
    case 'Hudson Automotive Group':
      return [
        'year',
        'display_price',
        'make',
        'model',
        'standardbody',
        'type',
        'extcolorgeneric',
        'drivetrain',
        'trim',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
        'option_package',
        'dealername',
      ];
    case 'Claremont Toyota':
    case 'Toyota of Huntington Beach':
    case 'Toyota Demo 3':
      return [
        'make',
        'model',
        'year',
        'trim',
        'option_package',
        'condition',
        'display_price',
        'extcolorgeneric',
        'standardbody',
        'drivetrain',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'dealer_offer',
        'int_colorgeneric',
      ];
    case 'Johnson City Toyota':
      return [
        'make',
        'model',
        'year',
        'trim',
        'option_package',
        'type',
        'display_price',
        'extcolorgeneric',
        'body',
        'drivetrain',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'dealer_offer',
        'int_colorgeneric',
        'priority_option',
        'dealername',
      ];
    case 'Vixen Honda Demo':
      return [
        'make',
        'model',
        'year',
        'trim',
        'option_package',
        'condition',
        'display_price',
        'extcolorgeneric',
        'standardbody',
        'drivetrain',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'dealer_offer',
        'int_colorgeneric',
      ];
    case 'Joseph Toyota of Cincinnati':
    case 'Rocky Mount Toyota':
      return [
        'type',
        'display_price',
        'make',
        'model',
        'extcolorgeneric',
        'standardbody',
        'drivetrain',
        'year',
        'trim',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
        'option_package',
      ];
    case 'Jaguar Demo':
    case 'Land Rover Demo':
    case 'Land Rover Princeton':
      return [
        'type',
        'make',
        'miles',
        'model',
        'extcolorgeneric',
        'standardbody',
        'year',
        'drivetrain',
        'trim',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
        'option_package',
      ];
    case 'Cole European Jaguar':
    case 'Cole European Land Rover':
      return [
        'type',
        'make',
        'miles',
        'model',
        'extcolorgeneric',
        'standardbody',
        'year',
        'drivetrain',
        'trim',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
      ];
    case 'Jaguar Ventura':
    case 'Land Rover Ventura':
    case 'Jaguar Cincinnati':
      return [
        'type',
        'display_price',
        'make',
        'miles',
        'model',
        'extcolorgeneric',
        'standardbody',
        'year',
        'drivetrain',
        'trim',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
        'option_package',
      ];
    case 'Land Rover Fairfield':
    case 'Jaguar Fairfield Certified Pre-Owned &amp; Service':
      return [
        'type',
        'make',
        'miles',
        'model',
        'extcolorgeneric',
        'standardbody',
        'year',
        'drivetrain',
        'trim',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
        'option_package',
      ];
    case 'Cincinnati Land Rover':
      return [
        'type',
        'display_price',
        'make',
        'miles',
        'model',
        'extcolorgeneric',
        'standardbody',
        'year',
        'drivetrain',
        'trim',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
        'option_package',
      ];
    case 'Monrovia CDJR':
      return [
        'type',
        'display_price',
        'make',
        'model',
        'extcolorgeneric',
        'standardbody',
        'drivetrain',
        'year',
        'trim',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
        'option_package',
        'dealername,',
        'comment4',
      ];
    case 'Viva Los Angeles CDJR':
      return [
        'type',
        'display_price',
        'make',
        'model',
        'extcolorgeneric',
        'standardbody',
        'drivetrain',
        'year',
        'trim',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
        'option_package',
      ];
    case 'I-10 Toyota':
    case 'Toyota of San Bernardino':
      return [
        'comment5',
        'type',
        'display_price',
        'make',
        'model',
        'extcolorgeneric',
        'standardbody',
        'drivetrain',
        'year',
        'trim',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
        'option_package',
      ];
    case 'Land Rover Cerritos':
    case 'Jaguar Cerritos':
      return [
        'type',
        'make',
        'model',
        'trim',
        'year',
        'standardbody',
        'extcolorgeneric',
        'drivetrain',
        'miles',
        'engdescription',
        'fueltype',
        'priority_option',
      ];
    case 'Mercedes Benz Demo':
      return [
        'type',
        'display_price',
        'make',
        'model',
        'extcolorgeneric',
        'standardbody',
        'drivetrain',
        'year',
        'trim',
        'miles',
        'engdescription',
        'fueltype',
        'priority_option',
      ];
    case 'Mercedes-Benz of West Chester':
    case 'Mercedes-Benz of Cincinnati':
      return [
        'model',
        'display_price',
        'standardbody',
        'dealername',
        'year',
        'extcolorgeneric',
        'drivetrain',
        'trim',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
      ];
    case 'Mercedes-Benz of West Covina':
    case 'Mercedes-Benz of Escondido':
    case 'Mercedes-Benz of Sacramento':
      return [
        'display_price',
        'make',
        'model',
        'extcolorgeneric',
        'standardbody',
        'drivetrain',
        'year',
        'trim',
        'miles',
        'engdescription',
        'fueltype',
        'priority_option',
        'dealername',
      ];
    case 'Mercedes-Benz of Rocklin':
      return [
        'model',
        'make',
        'display_price',
        'dealername',
        'year',
        'body',
        'extcolorgeneric',
        'drivetrain',
        'trim',
        'miles',
        'engdescription',
        'fueltype',
        'epahighway',
        'epacity',
        'priority_option',
      ];
    case 'Sierra Honda of Monrovia':
      return [
        'type',
        'display_price',
        'make',
        'model',
        'extcolorgeneric',
        'drivetrain',
        'year',
        'trim',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
        'dealername',
      ];
    case 'Gastonia Nissan_New':
      return [
        'year',
        'model',
        'body',
        'trim',
        'drivetrain',
        'miles',
        'type',
        'display_price',
        'make',
        'extcolorgeneric',
        'int_colorgeneric',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
      ];
    case 'Gastonia Nissan':
      return [
        'year',
        'make',
        'model',
        'display_price',
        'body',
        'miles',
        'drivetrain',
        'type',
        'extcolorgeneric',
        'int_colorgeneric',
        'trim',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
      ];
    case 'Strathmore Motors':
      return [
        'display_price',
        'make',
        'model',
        'int_colorgeneric',
        'body',
        'drivetrain',
        'dealername',
        'extcolorgeneric',
        'year',
        'trim',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
        'comment3',
      ];
    case 'Toyota of Las Vegas':
      return [
        'make',
        'model',
        'year',
        'trim',
        'option_package',
        'type',
        'display_price',
        'extcolorgeneric',
        'body',
        'drivetrain',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'int_colorgeneric',
        'priority_option',
      ];
    case 'Toyota Canada Demo':
      return [
        'type',
        'display_price',
        'year',
        'body',
        'make',
        'model',
        'trim',
        'priority_option',
        'extcolorgeneric',
        'int_colorgeneric',
        'engdescription',
        'drivetrain',
        'epacity',
        'epahighway',
        'dealername',
        'miles',
      ];
    case 'M&#039;Lady Nissan':
      return [
        'make',
        'model',
        'year',
        'trim',
        'option_package',
        'type',
        'display_price',
        'extcolorgeneric',
        'standardbody',
        'drivetrain',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'dealer_offer',
        'int_colorgeneric',
        'priority_option',
      ];
    case 'TriState Vans':
      return [
        'make',
        'model',
        'year',
        'trim',
        'option_package',
        'type',
        'display_price',
        'drivetrain',
        'miles',
        'engdescription',
        'fueltype',
        'dealer_offer',
        'priority_option',
      ];
    case 'Sierra CDJR Used Car Superstore':
      return [
        'make',
        'model',
        'year',
        'trim',
        'option_package',
        'type',
        'display_price',
        'extcolorgeneric',
        'body',
        'drivetrain',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'dealer_offer',
        'int_colorgeneric',
        'priority_option',
        'dealername',
      ];
    case 'Honda Kingsport_New':
    case 'Honda Morristown_New':
      return [
        'make',
        'model',
        'year',
        'trim',
        'option_package',
        'type',
        'display_price',
        'extcolorgeneric',
        'body',
        'drivetrain',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'dealer_offer',
        'int_colorgeneric',
        'priority_option',
      ];
    case 'Honda Kingsport':
    case 'Honda Morristown':
      return [
        'dealername',
        'make',
        'model',
        'year',
        'trim',
        'option_package',
        'type',
        'display_price',
        'extcolorgeneric',
        'body',
        'drivetrain',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'dealer_offer',
        'int_colorgeneric',
        'priority_option',
      ];
    case 'Mercedes-Benz of El Dorado Hills':
      return [
        'display_price',
        'make',
        'model',
        'extcolorgeneric',
        'body',
        'drivetrain',
        'year',
        'trim',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
        'option_package',
        'dealername',
      ];
    case 'Wolfe Cadillac Edmonton':
      return [
        'make',
        'model',
        'year',
        'trim',
        'option_package',
        'type',
        'display_price',
        'extcolorgeneric',
        'body',
        'drivetrain',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'dealer_offer',
        'int_colorgeneric',
        'priority_option',
        'dealername',
      ];
    case 'Envision CDJR West Covina':
      return [
        'type',
        'display_price',
        'make',
        'model',
        'extcolorgeneric',
        'body',
        'drivetrain',
        'year',
        'trim',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'priority_option',
        'option_package',
      ];
    default:
      return [
        'make',
        'model',
        'year',
        'trim',
        'option_package',
        'type',
        'display_price',
        'extcolorgeneric',
        'body',
        'drivetrain',
        'miles',
        'engdescription',
        'fueltype',
        'epacity',
        'epahighway',
        'dealer_offer',
        'int_colorgeneric',
        'priority_option',
      ];
  }
};
