import { hexToRgb, mix, hexToRgbValues } from '@utils/hex-to-rgb.util';

export const computeCssVariables = (siteConfig: SiteConfig) => {
  const primaryColor = siteConfig.colors.primary ?? '#1277ae';
  const secondaryColor = siteConfig.colors.secondary ?? '#181818';
  const fontPrimaryConfig = siteConfig.fonts.primary
    ? siteConfig.fonts.primary
    : 'open sans';
  const fontPrimary = `${fontPrimaryConfig}, Helvetica Neue, sans-serif`;
  const { header } = siteConfig.colors;
  const { headerBg } = siteConfig.colors;
  const { navbarBg } = siteConfig.colors;
  const { secondaryNavbarBg } = siteConfig.colors;
  const { contactNavbarBg } = siteConfig.colors;
  const { contactNavbar } = siteConfig.colors;
  const { navBannerBackground } = siteConfig.colors;
  const { navBannerFont } = siteConfig.colors;
  const { footerLogo } = siteConfig.colors;
  const { footerLogoBg } = siteConfig.colors;
  const { frontpageAboutUsBg } = siteConfig.colors;
  const { frontpageAboutUs } = siteConfig.colors;
  const { frontpageContactUs } = siteConfig.colors;
  const { frontpageContactUsBgPrimary } = siteConfig.colors;
  const { frontpageContactUsBgSecondary } = siteConfig.colors;
  const { findNextVehicleSearchBg } = siteConfig.colors;
  const { findNextVehicleSearch } = siteConfig.colors;
  const { findNextVehicleSearchBtn } = siteConfig.colors;
  const { findNextVehicleSearchBtnBg } = siteConfig.colors;
  const { carboxSpecialsRibbonBg } = siteConfig.colors;
  const { carboxSpecialsRibbon } = siteConfig.colors;
  const { headerTextColor } = siteConfig.colors;

  return `--font-family: ${fontPrimary};
  --font-family-secondary: 'open sans', sans-serif;
  --font-size: 16px;
  --primary-color: ${primaryColor};
  --brand-primary: ${primaryColor};
  --secondary-color: ${secondaryColor};
  --primary-color-rgb-values: ${hexToRgbValues(primaryColor)};
  --primary-color-rgb: ${hexToRgb(primaryColor)};
  --primary-color-light: ${mix(primaryColor, 'ffffff', 21)};
  --primary-color-lighter: ${mix(primaryColor, 'ffffff', 18)};
  --primary-color-lightest: ${mix(primaryColor, 'ffffff', 7.5)};
  --primary-color-hover: ${mix(primaryColor, 'ffffff', 80)};
  --primary-color-dark: ${mix(primaryColor, '000000', 90)};
  --primary-color-darker: ${mix(primaryColor, '000000', 75)};
  --primary-color-darkest: ${mix(primaryColor, '000000', 65)};
  --secondary-color-rgb-values: ${hexToRgbValues(secondaryColor)};
  --secondary-color-rgb: ${hexToRgb(secondaryColor)};
  --secondary-color-light: ${mix(secondaryColor, 'ffffff', 75)};
  --secondary-color-lighter: ${mix(secondaryColor, 'ffffff', 65)};
  --secondary-color-lightest: ${mix(secondaryColor, 'ffffff', 55)};
  --secondary-color-hover: ${mix(secondaryColor, 'ffffff', 80)};
  --secondary-color-dark: ${mix(secondaryColor, '000000', 90)};
  --secondary-color-darker: ${mix(secondaryColor, '000000', 75)};
  --secondary-color-darkest: ${mix(secondaryColor, '000000', 65)};

  --header: ${header};
  --headerBg: ${headerBg};
  --navbarBg: ${navbarBg};
  --secondaryNavbarBg: ${secondaryNavbarBg};
  --contactNavbarBg: ${contactNavbarBg};
  --contactNavbar: ${contactNavbar};
  --navBannerBackground: ${navBannerBackground};
  --navBannerFont: ${navBannerFont};
  --footerLogo: ${footerLogo};
  --footerLogoBg: ${footerLogoBg};
  --frontpageAboutUsBg: ${frontpageAboutUsBg};
  --frontpageAboutUs: ${frontpageAboutUs};
  --frontpageContactUs: ${frontpageContactUs};
  --frontpageContactUsBgPrimary: ${frontpageContactUsBgPrimary};
  --frontpageContactUsBgSecondary: ${frontpageContactUsBgSecondary};
  --findNextVehicleSearchBg: ${findNextVehicleSearchBg};
  --findNextVehicleSearch: ${findNextVehicleSearch};
  --findNextVehicleSearchBtn: ${findNextVehicleSearchBtn};
  --findNextVehicleSearchBtnBg: ${findNextVehicleSearchBtnBg};
  --carboxSpecialsRibbonBg: ${carboxSpecialsRibbonBg};
  --carboxSpecialsRibbon: ${carboxSpecialsRibbon};
  --text-color-header: ${headerTextColor};
  --text-color: #000;
  --black: #000000;
  --white: #ffffff;`.replace(/\n/gi, '');
};
